[package]
name = "hiko"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.28"
lettre = "0.10.4"
reqwest = "0.11.20"
rusqlite = "0.29.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
tempfile = "3.8.0"
tokio = { version = "1.32.0", features = ["full"] }
toml = "0.7.7"
uuid = { version = "1.4.1", features = ["v4", "fast-rng"] }
