[package]
name = "hiko"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.28"
lettre = "0.10.4"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
tempfile = "3.8.0"
tokio = { version = "1.32.0", features = ["full"] }
toml = "0.8.2"
uuid = { version = "1.4.1", features = ["v4", "fast-rng"] }
axum = "0.6.20"
surrealdb = "1.0.0"
async-trait = "0.1.74"
reqwest = "0.11.22"
