[package]
name = "hiko"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.11.18"
rusqlite = "0.29.0"
serde = {version = "1.0.183",  features = ["derive"]}
serde_json = "1.0.104"
tempfile = "3.7.0"
tokio = {version = "1.29.1", features = ["full"]}
toml = "0.7.6"
