[General]
port = 3000
#log_path = ""

[Database]
url = ""
user = ""
password = ""

[Task]
timeout = 5000

[Mail]
smtp_username = ""
smtp_password = ""
smtp_server = ""
smtp_port = 0
target_email = ""
